name: tamagochi_app
description: Tamagochi app.
# .well-known/assetlinks.json
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  dio: ^4.0.4
  firebase_core: ^1.21.1

  firebase_remote_config: ^2.0.16
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.3.1
  flutter_svg: ^1.0.3
  http: ^0.13.4
  json_annotation: ^4.4.0
  mwwm: ^2.0.0
  onesignal_flutter: ^3.4.1
  relation: ^3.1.0
  share_plus: ^4.0.10+1
  string_validator: ^0.3.0
  surf_injector: ^1.0.0
  surf_util: ^1.0.3


dev_dependencies:
  build_runner: ^2.1.7
  fake_async: ^1.2.0
  flutter_native_splash: ^2.0.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5
  retrofit_generator: ^4.0.1
  surf_lint_rules: ^1.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

fonts:
  - family: Righteous
    fonts:
      - asset: assets/font/Righteous-Regular.ttf