name: tamagochi_app
description: Tamagochi app.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  device_preview: ^1.0.0
  flutter:
    sdk: flutter

  flutter_svg: ^1.0.3
  mwwm: ^2.0.0
  relation: ^3.1.0
  surf_injector: ^1.0.0
  surf_util: ^1.0.3


dev_dependencies:
  fake_async: ^1.2.0
  flutter_native_splash: ^2.0.2
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

fonts:
  - family: Righteous
    fonts:
      - asset: assets/font/Righteous-Regular.ttf